### Problem 1

# > The `borealis` package comes with several build-in datasets. The object `Bombus.forewings` contains a  dataset of bumblebee forewing shapes digitized using the same landmarks you recently used.
# > How many specimens are present in this dataset? 

dim(Bombus.forewings$coords)

Bombus.forewings$specimen.number

Bombus.forewings$provenance$create.tps

# There are 99 specimens

# > What species are included? 

unique(Bombus.forewings$metadata$species)

# [1] "vag"   "imp"   "bimac" "terri" "tern"  "bor"   "ferv"  "san" 

# #### Challenge 1
# > And how many specimens represent each species?

c(with(Bombus.forewings$metadata, by(species,species,length)))

# bimac   bor  ferv   imp   san  tern terri   vag 
# 23     3     2    29     1    26     2    13 

# ### Problem 2
# 
# > Perform generalized Procrustes alignment of the `Bombus.forewings` dataset, using the methods and tools we discussed. Be aware that some data curation may be necessary. Use your discretion and check whether it is necessary to omit or reflect specimens, or to correct landmark errors made during digitization. Be sure to document any manual corrections in the data provenance. 
# > In your response to these questions, include an image of the aligned landmarks (the plot with gray and black dots generated by the `align.procrustes` function) and the data provenance (in markdown format) for the GPA step and any steps of data curation. 

# Always useful to look at the data first.

landmark.plot(Bombus.forewings, links = fw.links)

# Ensure that they're all oriented the same way.

wings <- align.reflect(Bombus.forewings, top.pt = 2, left.pt = 19, links = fw.links)

gpa <- align.procrustes(wings)

# The initial plot shows at least one dramatic outlier

gpa <- align.procrustes(wings, outlier.analysis = TRUE)
landmark.plot(wings, links = fw.links, specimen.number = c(1,57))

# Specimen 57 looks very weird. Not sure how, so it's best to just remove it.

cat(gpa$provenance$align.reflect)
cat(gpa$provenance$align.procrustes)

# ```
# ## Generalized Procrustes analysis
# 
# Performed by user `drangeli` with `borealis::align.procrustes` version 2022.10.20 on Thursday, 20 October 2022, 22:19:07
# 
# The following 1 specimens were removed after 1 rounds of outlier analysis: 
#   - FJ190828-002
# ````

# #### Problem 3
# 
# > Use the function `procrustes.distance` to compare the shapes of the first 3 specimens in the `Bombus.forewings` dataset after Procrustes alignment. Which two specimens are more similar?

landmark.plot(gpa, specimen.number = 1:3, links = fw.links)

procrustes.distance(gpa$gdf$coords[,,1], gpa$gdf$coords[,,2])
procrustes.distance(gpa$gdf$coords[,,2], gpa$gdf$coords[,,3])
procrustes.distance(gpa$gdf$coords[,,1], gpa$gdf$coords[,,3])

# Specimens 2 and 3 are most similar.

# #### Challenge 3
# 
# > Run this function [`procrustes.jackknife`] on your curated coordinate data from `Bombus.forewings` (not on the GPA-aligned data). Include the resulting image in your answer. Which landmarks are more variable? What explanations exist for these results?

procrustes.jackknife(wings, links = fw.links)

# Landmarks 5 and 17 have the lowest median Procrustes distance. This might reflect human error or variation among digitizers in their placement, or it could be that these landmarks vary among species in the dataset.


